# Generated by Django 5.0.2 on 2024-03-03 19:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_jugador_tecnico_remove_equipo_fundacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='fechaEntrega',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
    ]
