# Generated by Django 5.0.2 on 2024-03-03 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_equipo_fechaentrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='fechaEntrega',
        ),
    ]
